server {
  listen 80;
  server_name dev.tilt-us.com;

  location = /examples {
    return 301 /examples/;
  }

  location /examples/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://bevy-docs-beta:80/examples/;
  }

  location = /libraries/docs/bevy_extended_ui {
    return 301 /libraries/docs/bevy_extended_ui/;
  }

  location /libraries/docs/bevy_extended_ui/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://bevy-docs-beta:80/;
  }

  location / {
    return 404;
  }
}

server {
  listen 80;
  server_name tilt-us.com;

  location = /examples {
    return 301 /examples/;
  }

  location /examples/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://bevy-docs-release:80/examples/;
  }

  location = /libraries/docs/bevy_extended_ui {
    return 301 /libraries/docs/bevy_extended_ui/;
  }

  location /libraries/docs/bevy_extended_ui/ {
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_pass http://bevy-docs-release:80/;
  }

  location / {
    return 404;
  }
}
